### ISSUE TITLE
Needs Wiki for Design Consistency

### ISSUE THREAD

**Issue by crutchcorn** [trenta-io/trenta-icons#1]
Needs things such as light source, drop show, color palette, etc

**Comment by danielhickman** [comment]
+1

**Comment by 19kestier** [comment]
I agree. I've talked to @KevDoy about this before, but I'll talk with him and see what he thinks.

**Comment by KevDoy** [comment]
it's not a priority and way too early. 
Good designers will be able to imitate if they want to help.
Right now, like I said, it's too early. A design standard wouldn't help because other than the shapes and a few other attributes, everything is variable based on what looks good.
as you can see, the lighting changes to match compliment the color, item, or other feature of the icon.
That's the part about design. Not everything is like code where there is syntax to follow
That's why Numix's theme is kinda boring and too consistent. 
because if theres an icon they missed, it looks awful. I want an icon set that looks amazing, but can still live alongside other icons, unthemed.
too consistent makes that impossible.

I can make a design standard, but it wouldn't touch on anything except shapes, a few other things like angle of the square icons and so on. But if you can't imitate the style, there's no point really. If you look, the gradients and everything match, but they're different to work better with each specific color, etc.

Let me know if you have any questions. For now, this is closed.

**Comment by danielhickman** [comment]
No one knows about the gradients and what not. It **should** be a wiki too. It would help others create similar ones and rules to follow so that things don't look crazy different. Just my suggestion.

**Comment by KevDoy** [comment]
Daniel, if you had read what I just said - they vary. So making a standard would make everything "look crazy" because they would all look the same. It's too early.

**Comment by KevDoy** [comment]
Try recreating the icons and then tell me what kind of gradients you used, then we'll go from there.

**Comment by danielhickman** [comment]
I like the idea, but I am personally busy. I just like the idea of these
icon, and like the idea of consistency that won't require redoing any icons
for the sake of time. I hope you can do what you can do best to suit your
needs of doing that.

**Comment by KevDoy** [comment]
The reason I'm pushing back on this is because I'm a team of one right now. If you haven't seen the style, it's not close to exactly close to "being done" and we're struggling to get Alpha 3 out. This is not the time to waste time on a wiki. 

Like I said, if you're a designer and can interpret the design, please we welcome someone helping out and maybe even creating a wiki. 

To your last response, I am busy too. I'm going on yet another 12 hour work day. After that I'm working for a local business helping them with marketing and then I'll just get home in time to sleep because I have a 2 hour commute. I have a personal life. You telling me I have to create a design standard isn't only selfish because it's asking a guy who isn't paid to do this  but is doing this because for the love of design and because this is a hole in Linux that needs to be filled, but it's also selfish because you're telling me I'm wrong when I'm here a professional designer spending my time trying to get this product out to THE FANS. It's a waste of time at this point. End of discussion.

**Comment by KevDoy** [comment]
So please, don't give me "I am personally busy." and then you start asking for things. In the linux world (and hell, even the real world) if you want something, make it happen.

**Comment by danielhickman** [comment]
I'm very sorry, I didn't mean to come across as mean. I was just giving my
input. I am really busy, you should know very well that we can all get busy
from what I saw in you comment. Please I appreciate your work and time put
into this, but personally can't take part.

**Comment by KevDoy** [comment]
Got new designers. This has been added as a goal of the design team.

**Comment by KevDoy** [comment]
First basic version is up. Will continue to be a rolling project. 
https://trenta.io/brand.html
